# Traivis CI script
# Based on both
# https://whileimautomaton.net/2013/02/08211255
# and :h vader

language: vim
cache:
  directories:
    - $HOME/.rvm
    - $HOME/.vvm
before_install:
  - curl https://raw.githubusercontent.com/kana/vim-version-manager/master/bin/vvm | python - setup; true
  - source ~/.vvm/etc/login
  - vvm update_itself
  - vvm use vimorg--v8.0.1529 --install --with-features=huge
  -
  - rvm use 2.5.0 --install --binary --fuzzy

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/google/vim-maktaba.git
  sudo apt-get install vim -y

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=vim-maktaba
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/object.vader' > /dev/null
